name: CI/CD Pipeline - Build, Push and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: microservice

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug File Structure
      run: ls -R

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice:latest -f microservice/Dockerfile microservice/


    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/microservice:latest

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Kubernetes context
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: myCluster
        resource-group: myResourceGroup

    - name: Deploy to AKS
      run: |
        kubectl apply -f microservice/k8s/deployment.yaml
        kubectl apply -f microservice/k8s/service.yaml
